version: '3.8'

services:
  db:
    image: postgres:75-alpine
    environment:
      POSTGRES_DB: kthais_db
      POSTGRES_USER: kthais_user
      POSTGRES_PASSWORD: development_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
